spring:
  cloud:
    stream:
      bindings:
        # in
        correct-messages:
          destination: correctMessages
          content-type: application/json
          durable-subscription: correct-messages
          group: correct-messages
        incorrect-messages:
          destination: incorrectMessages
          content-type: application/json
          durable-subscription: incorrect-messages
          group: incorrect-messages
        reactive-process:
          destination: reactiveProcess
          content-type: application/json
          group: reactive-process
          durable-subscription: reactive-process
        # out
        reactive-messages:
          destination: reactiveMessages
          content-type: application/json
        reactive-end:
          destination: reactiveEnd
          content-type: application/json
server:
  port: 0
