spring:
  cloud:
    stream:
      bindings:
        error:
          destination: errors
        # in
        correct-messages:
          destination: correctMessages
          durable-subscription: correct-messages
          group: correct-messages
        incorrect-messages:
          destination: incorrectMessages
          durable-subscription: incorrect-messages
          group: incorrect-messages
        reactive-process:
          destination: reactiveProcess
          durable-subscription: reactive-process
        # out
        reactive-messages:
          destination: reactiveMessages
        reactive-end:
          destination: reactiveEnd
  output:
    ansi:
      enabled: always
server:
  port: 0
