spring:
  cloud:
    stream:
      bindings:
        error:
          destination: errors
        output:
          destination: reactiveAggrigate
#          content-type: application/json
  kafka:
    consumer:
      group-id: streaming-reactive-producer
      auto-offset-reset: earliest
  output:
    ansi:
      enabled: always
server:
  port: 0
