spring:
  cloud:
    stream:
      bindings:
        error:
          destination: errors
        output:
          destination: reactiveAggrigate
          content-type: application/json
server:
  port: 0
