service:
- docker
sudo: required
group: trusty_lts
install: true
language: java
jdk:
- oraclejdk8
- openjdk8
before_install:
- sudo apt update -y || true
- sudo apt install docker-ce python-pip
- sudo pip install docker-compose
script:
- bash gradlew
- bash gradlew integrationTests -Penv=kafka
- bash gradlew integrationTests -Penv=rabbit
#cache:
#  directories:
#  - $HOME/.gradle/
#  - .gradle/
