service:
- docker
sudo: required
group: trusty_lts
install: true
language: java
jdk: oraclejdk8
before_install:
- sudo apt update -y || true
- sudo apt install docker-ce python-pip curl bash wget
- sudo pip install docker-compose
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 2181 9092 8080 5432 80 5673 15672 61613
script:
- bash gradlew composeUp
- bash gradlew integrationTests -Pprofile=rabbit
# kafka for some reasons not worked anymore...
#- wget -O /tmp/kafka.jar https://github.com/daggerok/embedded-kafka/raw/mvn-repo/daggerok/embedded-kafka/0.0.1/embedded-kafka-0.0.1.jar
#- java -jar /tmp/kafka.jar &
#- bash gradlew integrationTests -Pprofile=kafka
cache:
  directories:
  - $HOME/.gradle/
  - .gradle/
