group: edge
install: true
language: java
jdk: oraclejdk8
env:
  SPRING_PROFILES_ACTIVE: dev
before_install:
  # gradle
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk selfupdate
  - touch "$HOME/.sdkman/etc/config"
  - sed -i -e 's/^sdkman_auto_answer=false$/sdkman_auto_answer=true/g' "$HOME/.sdkman/etc/config"
  - sdk use gradle
  - sdk install gradle
  - mkdir -p "$HOME/.sdkman/etc"
  - sdk use gradle
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
script:
  - gradle clean build
  - gradle bootRun-service &
  - sleep 10
  - gradle bootRun-client &
  - sleep 10
  - echo "you should be abe to see hi"
  - sleep 5
after_script:
  - gradle --stop
cache:
  directories:
    - $HOME/.gradle/
    - .gradle/
