service:
- docker
sudo: required
group: trusty_lts
install: true
language: java
jdk: oraclejdk8
before_install:
- sudo apt update -y || true
- sudo apt install docker-ce python-pip curl bash
- sudo pip install docker-compose
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 2181 9092 8080 5432 80 5673 15672 61613
script:
- bash gradlew
cache:
  directories:
  - $HOME/.gradle/
  - .gradle/
