version: '2.1'
services:
  rabbitmq:
    container_name: rabbitmq
    image: healthcheck/rabbitmq:alpine
    ports:
      - 15672:15672
      - 61613:61613
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - backoffice
      - development
volumes:
  rabbitmq-data: {}
networks:
  backoffice:
    driver: bridge
  development:
    driver: bridge
