spring:
  cloud:
    stream:
      bindings:
        error:
          destination: errors
        input:
          #consumer.headerMode: raw
          destination: messages
          durable-subscription: aggregator
        output:
          #producer.headerMode: raw
          destination: aggregateMessages
  output:
    ansi:
      enabled: always
server:
  port: 0
