spring:
  cloud:
    stream:
      bindings:
        input:
          destination: reactiveAggrigate
          content-type: application/json
          durable-subscription: reactive-aggregator
        output:
          destination: reactiveProcess
          content-type: application/json
server:
  port: 0
