spring:
  cloud:
    stream:
      bindings:
        error:
          destination: errors
        input:
          destination: reactiveAggrigate
          durable-subscription: reactive-aggregator
        output:
          destination: reactiveProcess
  output:
    ansi:
      enabled: always
server:
  port: 0
