spring:
  cloud:
    stream:
      bindings:
        error:
          destination: errors
        messages:
          destination: messages
  output:
    ansi:
      enabled: always
server:
  port: 0
