spring:
  cloud:
    stream:
      bindings:
        error:
          destination: errors
        messages:
          destination: messages
          content-type: application/json
#          # consumers: spring.cloud.stream.bindings.messages.group: <some-group>
#          producer:
#            partition-key-expression: payload.id
#            partition-count: 10
server:
  port: 0
