spring:
  cloud:
    stream:
      bindings:
        error:
          destination: errors
        correctMessages:
          destination: correctMessages
        incorrectMessages:
          destination: incorrectMessages
        aggregateMessages:
          destination: aggregateMessages
  output:
    ansi:
      enabled: always
server:
  port: 0
