spring:
  cloud:
    stream:
      bindings:
        error:
          destination: errors
        correctMessages:
          destination: correctMessages
#          content-type: application/json
        incorrectMessages:
          destination: incorrectMessages
#          content-type: application/json
        aggregateMessages:
          destination: aggregateMessages
#          content-type: application/json
  kafka:
    consumer:
      group-id: streaming-consumer
      auto-offset-reset: earliest
  output:
    ansi:
      enabled: always
server:
  port: 0
