version: "2.1"

services:

  kafka:
    image: daggerok/kafka:v9
    environment:
      ZOOKEEPER_PORT: 2181
      ZOOKEEPER_DIR: /home/appuser
      KAFKA_PORT: 9092
      KAFKA_TOPICS: errors,messages,aggregateMessages,correctMessages,incorrectMessages,messages-processor,reactiveAggrigate,reactive-aggregator,reactiveProcess,reactive-end,reactiveEnd,incorrect-messages,reactiveMessages,reactive-process
      HTTP_PORT: 8080
      HTP_CONTEXT: /
    ports:
    - "8080:8080"
    - "9092:9092"
    - "2182:2182"
    volumes:
    - "kafka-data:/home"
    networks: [backing-services]

volumes:
  kafka-data: {}

networks:
  backing-services:
    driver: bridge
