spring:
  cloud:
    stream:
      bindings:
        error:
          destination: errors
        messages:
          destination: messages
          # only one processor instance should handle input messages
          group: messages-processor
          # we want to not loose any messages in case of zero-instances
          durable-subscription: messages-processor
        correctMessages:
          destination: correctMessages
        incorrectMessages:
          destination: incorrectMessages
  output:
    ansi:
      enabled: always
server:
  port: 0
