spring:
  cloud:
    stream:
      bindings:
        correctMessages:
          destination: correctMessages
          content-type: application/json
        incorrectMessages:
          destination: incorrectMessages
          content-type: application/json
server:
  port: 0
